const data = {
  products: [
    {
      name: "Bratitude",
      slug: "bratitude",
      category: "lips",
      images: "/images/LipProduct1.jpg", //679px x 829px
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      name: "Paradise Pink",
      slug: "paradise-pink",
      category: "lips",
      images: "/images/LipProduct2.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      name: "Cosmic Pink",
      slug: "comsic-pink",
      category: "lips",
      images: "/images/LipProduct3.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      name: "Glam Bratz",
      slug: "glam-bratz",
      category: "lips",
      images: "/images/LipProduct4.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      name: "Forever Diamonds",
      slug: "forever-diamonds",
      category: "lips",
      images: "/images/LipProduct5.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      name: "Yazmin",
      slug: "yazmin",
      category: "lips",
      images: "/images/LipProduct6.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      name: "Rock Angelz",
      slug: "rock-angelz",
      category: "lips",
      images: "/images/LipProduct7.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
  ],
};

export default data;
