const data = {
  products: [
    {
      //_id: "1",
      name: "Bratitude",
      slug: "bratitude",
      category: "lips",
      images: "/images/LipProduct1.jpg", //679px x 829px
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "2",
      name: "Paradise Pink",
      slug: "paradise-pink",
      category: "lips",
      images: "/images/LipProduct2.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "3",
      name: "Cosmic Pink",
      slug: "comsic-pink",
      category: "lips",
      images: "/images/LipProduct3.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "4",
      name: "Glam Bratz",
      slug: "glam-bratz",
      category: "lips",
      images: "/images/LipProduct4.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "5",
      name: "Forever Diamonds",
      slug: "forever-diamonds",
      category: "lips",
      images: "/images/LipProduct5.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "6",
      name: "Yazmin",
      slug: "yazmin",
      category: "lips",
      images: "/images/LipProduct6.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "7",
      name: "Rock Angelz",
      slug: "rock-angelz",
      category: "lips",
      images: "/images/LipProduct7.jpg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "8",
      name: "Cateye",
      slug: "cateye",
      category: "lashes",
      images: "/images/Lash1.jpg",
      price: 15,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "9",
      name: "Carmen",
      slug: "carmen",
      category: "lashes",
      images: "/images/Lash2.jpg",
      price: 15,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "10",
      name: "Big One",
      slug: "big-one",
      category: "lashes",
      images: "/images/Lash3.png",
      price: 15,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "11",
      name: "Big Purr",
      slug: "big-purr",
      category: "lashes",
      images: "/images/Lash4.png",
      price: 15,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "12",
      name: "Glitter Snatch",
      slug: "glitter-snatch",
      category: "lashes",
      images: "/images/Lash5.png",
      price: 15,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "13",
      name: "Platinum",
      slug: "platinum",
      category: "lashes",
      images: "/images/Lash6.png",
      price: 15,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
    {
      //_id: "14",
      name: "Crysalis",
      slug: "crysalis",
      category: "lashes",
      images: "/images/Lash7.jpg",
      price: 15,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dolor sit amet",
    },
  ],
};

export default data;
